### PR TITLE
apply first-party protections to adguard japanese filters

### PR DESCRIPTION
**Pull request by antonok-edm**

### CODE REVIEW

**Review by ryanbr — COMMENTED** [review]
We shouldn't need this imo

**Comment by ShivanKaul** [comment]
There's a check_format failure @antonok-edm

**Comment by ShivanKaul** [comment]
Just a note here that there are potential webcompat concerns with this change.

**Comment by antonok-edm** [comment]
that's... not a formatting issue :thinking:

**Comment by eredotpkfr** [comment]
Hey @antonok-edm, sorry for reaching out you in here 😢 Do you still maintaning `enum_dispatch` package? We prepared [this pr](https://gitlab.com/antonok/enum_dispatch/-/merge_requests/39) for a new feature, actually I need that feature. Can you able to look at it? I tried to reach you on keybase but I couldn't

**Pull request merged**
