### PR TITLE
add Mobile Notifications list

### PR DESCRIPTION
**Pull request by antonok-edm**
~Updated PEM still needs to be uploaded to Jenkins~ ready to go

### CODE REVIEW

**Review by ryanbr — COMMENTED** [review]
Has the wrong url, didn't relise this PR was created https://github.com/brave/adblock-resources/pull/78 is valid however

**Comment by antonok-edm** [comment]
@ryanbr ah you're right :sweat_smile: fixed

this PEM is both in 1password and Jenkins, shall we use this one instead?

**Comment by ryanbr** [comment]
Sure okay @antonok-edm

**Review by ryanbr — APPROVED** [review]
Looks fine

**Pull request merged**
