### PR TITLE
.

### PR DESCRIPTION
**Pull request by TEMP-ad**

### CODE REVIEW

**Comment by TEMP-ad** [comment]
You can verify that it is the same Scriptlet as the master from TwitchAdSolutions, the only thing I did was to remove the first line `twitch-videoad.js text/javascript` which is incompatible with the way Scriptlets work in Brave.

**Comment by TEMP-ad** [comment]
@ShivanKaul

**Comment by TEMP-ad** [comment]
Scriptlets were updated few days ago:

Fix FrankerFaceZ loading issue https://github.com/pixeltris/TwitchAdSolutions/commit/2eefb984c10ba64e9528b8cf4350d5fab653bd3a
Fix regex for backup url https://github.com/pixeltris/TwitchAdSolutions/commit/b8fb2c38925f64627e14e3ac39c1e69003449d83
Fix video-swap-new error 1000 on midrolls https://github.com/pixeltris/TwitchAdSolutions/commit/644ac7a8217880597db52b506ae4d3ded287bedc

**Comment by TEMP-ad** [comment]
@ryanbr 

Can you take a look at this and tag whoever needs to check it? When you did your PR, you didn't update the scriptlets to the latest, and they got updated few days ago as well.

I only removed the `twitch-videoad.js text/javascript`, I have been doing that on my side to run these Scriptlets for more than a year and a half inside Brave.

I think implementing this is good and should be priority, yesterday I had someone asking "Does your adblocker work with Youtube ads", and while it is easy to do with uBlock and scriptlets, saying "yes, Brave adblocker does" would bring many users who want no ads in Twitch, even if it is a tricky mode to avoid the ads, we can't be too picky about it.

`video-swap-new` is the one that needs these latest updates, but the 2 months old updates made vaft better, plus pixeltris cleaned code based on Brave Team feedback and that wasn't merged either.

**Comment by TEMP-ad** [comment]
Whatever... This is dumb.

So what is the point of having PR set to anyone if you are just going to ignore people's submitted PRs? it's not about 'merging' and accept every change, it's about reviewing them and see if the changes are wanted or not.

It's so disrespectful to users, to have their PRs simply ignored, because YOU want them to be ignored, it's simply having a low class and no connection with the community that might want to 'help you' by submitting these PRs.

Yes, it is not even my job, but why would a comment in a PR said that the "Re-sync with latest changes in https://github.com/pixeltris/TwitchAdSolutions/commit/044d1fb3bb88a19ab718603069354d43eeba7015 " in https://github.com/brave/adblock-resources/pull/160#issuecomment-2071214031 when that was not the case? and then I try to correct that by submitting this PR and it gets ignored?

Not just that, you made pixeltris waste his time cleaning the code for the scriptlet and you still don't care to merge those changes, but then when I submit this PR is just ignored? and you can't just close it and move on?

Why have the repositories set to _anyone can submit PRs_ then?

Not just that, it is always the same waste of time and annoying stuff.

Reporting bugs that never get properly assigned, and then you tag people and they completely ignore the issues too. There are few counted Brave Devs that care and read when they are tagged, because I have to tag them because if not they never know there is a bug or something... but some get tagged and don't care.

believe me, nobody wants to report bugs, but Brave QA team is so mediocre that users have to find the bugs, nobody is even properly testing half PRs, because I always find something to report, I don't blame the one making the feature or whatever, I blame the ones that can't test things before the PR gets merged, this is why Nightly on Windows is better than MacOS and Linux, because someone actually reports bugs, even if I don't want to.

But most of you seem like you just want to make people waste their times, because when I make issues for any developer outside the "good known ones" I expect nothing but wasting me time and I am rarely wrong.

People have made valid issues for many things, and you don't even care to see them, even if you are requesting them, you just ignore the issues, so what is the point to ask users to make PR or even allow users to make issues?

Invalid, duplicate and useless issues stay opened, and the good ones get ignored... that's a lovely combination!.

Someone was asked by @bsclifton to create an Issue to prioritize an obvious security risk like not having VPN properly installed without admin rights in a Per User installation, and then what? the issue got ignored, still not implemented as far as I know, which means people are forced to install with administrator rights a BROWSER, just to get the benefits of the VPN they just paid? And the problem is not that the issue is not fixed, is that the Issue was completely ignored, even when it was "just make an issue".
So it is not an imagination, I have seen it many times. It's like when Manifestv3 extensions with DNR weren't working properly and it required 7 months and 400 comments to get it fixed, when it was a Brave issue.

So, It's always the similar nonsense with a lot of "brave team" members, ignoring issues, nor assigning them, ignoring being tagged.

Recently I reported and even gave the version where Brave started having issues with components when starting Brave with admin rights because the permissions would not be inherited properly and it got ignored, until I closed my issue with all the information about it, and it was ignored by ShivanKaul who obviously saw my comment and didn't even care to see it, nor bsclifton or anyone tagged in the old PR I ended up removing anyway. But if it was some issue made by a Brave team member even for the most useless stuff like AIChat, it would get prioritized, just like anything, Brave is full of bugs, inconsistencies in the UI and problems and incomplete features and the crap gets prioritized over making the existing features actually work.

It's just annoying because you could just avoid allowing random users like me to submit PRs, and just leave it to your little club, even if sometimes the whole "you can submit a PR" is thrown by you and it is just nonsense and a waste of time for users because even the simplest PR gets ignored. If you don't want people to do it, this why so many controls exist for repositories.

I don't even need this stupid PR, I just do it so people can enjoy adfree Twitch, I have sideloaded these and other scriptlets myself for almost 2 years, so I don't need this, I just do it because probably I care more about people and try to push something useful, instead of useless AIChat and other useless features, while leaving other features unfinished, buggy, and you don't do anything to fix what people report and still no uBo parity for so many rules that are still incompatible like $all, $to $popup which are more important than Action operators and Procedural Cosmetics.

I have reported too many issues around Brave and it is always the same devs that care about the reports like sangwoo108, tmancey, goodov, but the others simply don't care, and I don't care what their excuse is. a week for this PR that should have been merged or closed days ago, it's just a waste of time. There is nothing worst than dealing with 'adblocking people' Gorhill/uBlock people or Easylist... so it's like a level of worst self entitled people.

The only reason why I use Brave is the adblocker, and that's something I can do everything by myself, my scriptlets, my lists, my fixes, my turn off of default lists... And believe me, it is not because Brave adblocker is better than other adblockers, it is because  Brave applies cosmetics faster than uBlock and i hate flickering in the cosmetics, that's the only reason, anything else works as similar as uBlock.

So that's how much I don't care. I am sure you would get more users by saying "Avoid Twitch ads after today by using Experimental list" than AIChat and Bitcoin support and more ads in the browser and web3 and all.

But I really don't care. I am out of this BS.

**Comment by ShivanKaul** [comment]
This PR was submitted last week. We need to review all code that will get shipped in Brave for bugs and security issues like was done for https://github.com/brave/adblock-resources/pull/160; note that this review improved the upstream twitch script [last time](https://github.com/brave/adblock-resources/pull/160#issuecomment-2076175558) which benefits the whole filter list community. Brave regularly takes outside contributions; I personally review PRs by external researchers all the time and we find ways to make this process easier while making sure external contributions match our security requirements. Not all of this deliberation is public. Lack of chatter on an issue does not mean that it is not being worked on. You should always feel free to re-prod on an issue if you haven't seen an update in a while, we'll get back to you. 

> Recently I reported and even gave the version where Brave started having issues with components when starting Brave with admin rights because the permissions would not be inherited properly and it got ignored, until I closed my issue with all the information about it, and it was ignored by ShivanKaul who obviously saw my comment and didn't even care to see it, nor bsclifton or anyone tagged in the old PR I ended up removing anyway.

I'm not sure which issue you're referring to but we've already been discussing this on issue 38609.

What is not okay is attacking Brave employees.

**Comment by bsclifton** [comment]
@TEMP-ad thanks for the PR. I definitely appreciate the passion you have - but I hope you can understand we're trying our best here. I'd like to ask you to take a deep breath for a moment.

We're a smaller company, not a big outfit like Google. At the time I'm writing this, [we have 7458 open issues in `brave-browser`](https://github.com/brave/brave-browser/issues). We do our best to triage these (how many people does it impact, how severe is the impact, etc). We prioritize fixing broken features, crashes, bugs, and localization errors fairly high. You can see the corresponding `P1` / `P2` / `P3` / etc labels on issues there. We also try to map into a GitHub project board.

Each product has an owner and I work with those folks to prioritize the issues and get things fixed. There's a lot more I wish we could do, but unfortunately we only have a certain amount of resources available.

You're not alone in thinking that because your issue hasn't gotten a response that nobody cares. But I'd like to try and convince you that this IS NOT the case. I personally have over 7000 GitHub notifications that I have not acknowledged yet and I try my best to get through these in addition to getting work done. We're doing our best - the process I shared (opening an issue) has the best chance of success because we have people actively polling issues and triaging.

Thanks again for your submission. I'll leave it to @ShivanKaul for what next step we have. But please let's be more considerate of the folks here. It's really easy to get angry about things - I understand. But we are trying. If we're not able to meet your expectations, I'm sorry. But lets keep things civil please.

**Pull request closed without merging**
